import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Script from "next/script";
// pages/_app.js
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ElianLaw",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        <Script
          id="translate"
          dangerouslySetInnerHTML={{
            __html: `
                function googleTranslateElementInit() {
                  new google.translate.TranslateElement({ pageLanguage: 'en' }, 'google_translate_element');
                }
              `,
          }}
        />
        <Script
          type="text/javascript"
          src={`https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit`}
        />
      </body>
    </html>
  );
}
