import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
// pages/_app.js
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ElianLaw',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
